# Generated by Django 3.0.5 on 2020-05-02 21:05

from django.db import migrations


def create_cards(apps, schema_editor):
    Card = apps.get_model('setback', 'Card')
    print(Card.rank.field.choices)
    for suit, _ in Card.suit.field.choices:
        for rank, _ in Card.rank.field.choices:
            card = Card.objects.create(suit=suit, rank=rank)
            card.save()

class Migration(migrations.Migration):

    dependencies = [
        ('setback', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_cards)
    ]
